{#
# Parameters:
# - marine_region_id: The ID of the marine region to filter by.
# - marine_region: The name of the marine region to filter by.
# - observatories: The list of observatories to filter by (optional).
# - depth: The depth range to filter by (optional).
#   depth is a dict with keys value and operator.
# - contact: list of names of people or organizations to filter by (optional).
# - datetime_begin: The start date for the sampling (inclusive).
# - datetime_end: The end date for the sampling (inclusive).
# - sampling_method: The method of sampling to filter by.
#}
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT
  ?obs_id
  ?env_package
  ?tot_depth_water_col
  ?geo_loc_name
  (GROUP_CONCAT(DISTINCT ?loc_regional_; SEPARATOR=";") AS ?loc_regional_mrgid)
  ?ENA_accession_number_umbrella
  ?latlonpoint
  ?organization
  ?organization_country
  ?contact_name
  ?contact_email
WHERE {
    # link observatory
    ?obs_id_id a emobon:Observatory .
    # Optional: name of observatory
    OPTIONAL { ?obs_id_id emobon:observatoryId ?obs_id . }
    {% if obs_id %}
    ?obs_id onto:fts ("{{ obs_id | join('~5 ') }}~5") .
    {%- endif -%}
    # Optional: water column depth
    OPTIONAL { ?obs_id_id emobon:waterColumnDepth/qudt:numericValue ?tot_depth_water_col . }

    OPTIONAL { ?obs_id_id emobon:enaStudyAccNum ?ENA_accession_number_umbrella}
    OPTIONAL { ?obs_id_id emobon:geoLocation/<http://www.opengis.net/ont/geosparql#asWKT> ?latlonpoint}
    
    # optional organization and contact information
    OPTIONAL { 
      ?obs_id_id <https://schema.org/contactPoint> ?org . 
      ?org a emobon:Organization .
      ?org <https://schema.org/legalName> ?organization .
      OPTIONAL {
        ?org <https://schema.org/address>/<https://schema.org/addressCountry> ?organization_country .
      }
      OPTIONAL {
        ?org <https://schema.org/member>/<https://schema.org/name> ?contact_name .
        ?org <https://schema.org/member>/<https://schema.org/email> ?contact_email .
      }
    }

    # contact info without org
    OPTIONAL { 
      ?obs_id_id <https://schema.org/contactPoint> ?person . 
      ?person a <https://schema.org/Person> .
      ?person <https://schema.org/name> ?contact_name .
      ?person <https://schema.org/email> ?contact_email .
    }
    
    # Optional: location
    OPTIONAL { ?obs_id_id emobon:location ?location . }

    # Optional: marine region
    OPTIONAL { ?obs_id_id emobon:marineRegion ?loc_regional_ . }
    {% if loc_regional_mrgid %}
    FILTER regex(str(?loc_regional_mrgid), "{{ loc_regional_ }}") .
    {%- endif -%}
    # Optional: geo_loc_name
    OPTIONAL { ?obs_id_id emobon:originCountry ?geo_loc_name . }
    # Optional: sample type
    OPTIONAL { ?obs_id_id emobon:sampleType ?env_package . }
    {% if env_package %}
    FILTER(str(?env_package), "{{ env_package }}") .
    {%- endif -%}
}
GROUP BY ?obs_id ?env_package ?tot_depth_water_col ?geo_loc_name ?ENA_accession_number_umbrella ?latlonpoint ?organization ?organization_country ?contact_name ?contact_email